version: '3'
services:
  db:
    image: postgres
    container_name: uniao_deposito
    environment:
      - POSTGRES_DB=UNIAODEP
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    restart: always
    ports:
      - '5432:5432'
