/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.InterfaceController;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jpedr
 */
public class UniaoDeposito extends javax.swing.JFrame {

    /**
     * Creates new form UniaoDeposito
     */
    
    private InterfaceController interfaceController;
    
    public UniaoDeposito(InterfaceController interfaceController) {
        this.interfaceController = interfaceController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Produto = new javax.swing.JMenu();
        CadastrarProduto = new javax.swing.JMenuItem();
        ListarProduto = new javax.swing.JMenuItem();
        Cliente = new javax.swing.JMenu();
        CadastrarCliente = new javax.swing.JMenuItem();
        ListarCliente = new javax.swing.JMenuItem();
        Venda = new javax.swing.JMenu();
        RealizarVenda = new javax.swing.JMenuItem();
        ListarVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Produto.setText("Produto");

        CadastrarProduto.setText("Cadastrar");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });
        Produto.add(CadastrarProduto);

        ListarProduto.setText("Listar");
        ListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProdutoActionPerformed(evt);
            }
        });
        Produto.add(ListarProduto);

        jMenuBar1.add(Produto);

        Cliente.setText("Cliente");

        CadastrarCliente.setText("Cadastrar");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        Cliente.add(CadastrarCliente);

        ListarCliente.setText("Listar");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });
        Cliente.add(ListarCliente);

        jMenuBar1.add(Cliente);

        Venda.setText("Venda");

        RealizarVenda.setText("Realizar Venda");
        RealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVendaActionPerformed(evt);
            }
        });
        Venda.add(RealizarVenda);

        ListarVendas.setText("Listar Vendas");
        ListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarVendasActionPerformed(evt);
            }
        });
        Venda.add(ListarVendas);

        jMenuBar1.add(Venda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        interfaceController.janCadProduto();
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        interfaceController.janCadCliente();
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void RealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVendaActionPerformed
        interfaceController.janRealizarVenda();
    }//GEN-LAST:event_RealizarVendaActionPerformed

    private void ListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProdutoActionPerformed
         interfaceController.janListarProduto();
    }//GEN-LAST:event_ListarProdutoActionPerformed

    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
        interfaceController.janListarCliente();
    }//GEN-LAST:event_ListarClienteActionPerformed

    private void ListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarVendasActionPerformed
        interfaceController.janListarVenda();
    }//GEN-LAST:event_ListarVendasActionPerformed

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem ListarCliente;
    private javax.swing.JMenuItem ListarProduto;
    private javax.swing.JMenuItem ListarVendas;
    private javax.swing.JMenu Produto;
    private javax.swing.JMenuItem RealizarVenda;
    private javax.swing.JMenu Venda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
